server:
  port: 8081
  servlet:
    encoding:
     charset: UTF-8
   
spring:
  web:
    resources:
      static-locations: META-INF:/resources, classpath:/resources, classpath:/static, classpath:/static/dist
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://study-imho.duckdns.org:5432/imho
    platform: postgres
    username: imho_client
    password: '!mho$Client' 
  # jpa properties
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true